"""added kratjes table

Revision ID: 0751b0091641
Revises: 25c77a0ee915
Create Date: 2021-06-05 09:35:07.248437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0751b0091641'
down_revision = '25c77a0ee915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Kratjes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bet_description', sa.String(), nullable=True),
    sa.Column('stake', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Kratjes')
    # ### end Alembic commands ###
