"""add insult table

Revision ID: 25c77a0ee915
Revises: 
Create Date: 2021-05-23 18:56:14.982396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c77a0ee915'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Insult',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insult', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Insult')
    # ### end Alembic commands ###
