"""add itemlist position on item

Revision ID: 5470ea9c2386
Revises: 6efe18781a03
Create Date: 2021-09-02 14:51:07.181594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5470ea9c2386'
down_revision = '6efe18781a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Item', sa.Column('item_list_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Item', 'item_list_position')
    # ### end Alembic commands ###
