"""update kratjes table

Revision ID: 6efe18781a03
Revises: 0751b0091641
Create Date: 2021-07-10 15:20:42.491079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efe18781a03'
down_revision = '0751b0091641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ItemList', sa.Column('episode_date', sa.DateTime(), nullable=True))
    op.add_column('Kratjes', sa.Column('better', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Kratjes', 'better')
    op.drop_column('ItemList', 'episode_date')
    # ### end Alembic commands ###
